apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alert
  labels:
    prometheus: server
data:
  alert.rules.yml: |
    groups:
    - name: kubernetes
      rules:
      - alert: PodDown
        expr: kube_pod_status_phase{phase="Failed"} == 1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is down"
          description: "{{ $labels.namespace }}/{{ $labels.pod }} is down for more than 1 minute."
