apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    prometheus: server
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['192.168.49.2:31246']
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics:8080']
    rule_files:
          - /etc/prometheus/rules/alert.rules.yml